out_dir:
    '/Users/csifuentes/Documents/rnaseq-demo'
input_dir:
    fastq: '/Users/csifuentes/Documents/fastq-input/rnaseq_raw_data'
    genome_fasta: '/Users/csifuentes/Documents/fastq-input/rnaseq_raw_data/indexes/Homo_sapiens.GRCh38.dna.chromosome.19.fa'
    genome_gtf: '/Users/csifuentes/Documents/fastq-input/rnaseq_raw_data/indexes/hg38chr19.gtf'
thread_info:
    alignment: 8
    fastqc: 6
    index: 8
    trim: 8
    deeptools: 8
    pepr: 8
    homer: 8
trim:
    trimq: 20
    minlen: 30

